version: '3.7'

services:
  dm_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgres/data
  django:
    container_name: dm_movie
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/django-movie/manage.py migrate --noinput &&
              python /usr/src/django-movie/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/usr/src/django-movie
    ports:
      - 8080:8080
    depends_on:
      - dm_db
volumes:
  pg_data:
