version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn test_auth.wsgi:application --bind 0.0.0.0:8080
    expose:
      - 8080
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: