# Generated by Django 3.0.5 on 2020-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text='указывать в минутах', verbose_name='Продолжительность фильма'),
        ),
    ]
