# Generated by Django 3.0.5 on 2020-04-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
