# Generated by Django 3.0.5 on 2020-04-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200423_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age_ru',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age_uk',
        ),
    ]
