# Generated by Django 3.0.5 on 2020-04-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200423_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='title_uk',
        ),
    ]
