# Generated by Django 3.0.5 on 2020-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200423_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Example', max_length=100, verbose_name='Имя'),
        ),
    ]
