# Generated by Django 3.0.5 on 2020-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=25, verbose_name='Фамилия'),
        ),
    ]
