# Generated by Django 3.0.5 on 2020-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0002_auto_20200410_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
