# Generated by Django 3.0.5 on 2020-04-10 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0005_auto_20200410_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, help_text='YYYY-MM-DD format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='localuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
